[package]
name = "jpv"
version = "0.0.0"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "Japanese Dictionary by John-John Tedro"

[features]
bundle = ["rust-embed", "mime_guess", "webbrowser"]
bundle-database = ["rust-embed", "mime_guess", "webbrowser"]

[dependencies]
anyhow = "1.0.75"
axum = "0.6.20"
tokio = { version = "1.33.0", features = ["full"] }
lib = { path = "../lib" }
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.17", features = ["env-filter"] }
serde = { version = "1.0.189", features = ["derive"] }
clap = { version = "4.4.6", features = ["derive"] }
tower-http = { version = "0.4.4", features = ["cors"] }
musli-zerocopy = { version = "0.0.89" }

rust-embed = { version = "8.0.0", optional = true }
mime_guess = { version = "2.0.4", optional = true }
webbrowser = { version = "0.8.12", optional = true }

[target.'cfg(unix)'.dependencies]
memmap = "0.7.0"

[package.metadata.generate-rpm]
assets = [
    { source = "target/release/jpv", dest = "/usr/bin/jpv", mode = "755" },
    { source = "desktop/se.tedro.JapaneseDictionary.desktop", dest = "/usr/share/applications/se.tedro.JapaneseDictionary.desktop", mode = "644" },
    { source = "desktop/se.tedro.JapaneseDictionary.png", dest = "/usr/share/icons/hicolor/256x256/apps/se.tedro.JapaneseDictionary.png", mode = "644" },
    # { source = "desktop/se.tedro.JapaneseDictionary.service", dest = "/usr/share/dbus-1/services/se.tedro.JapaneseDictionary.service", mode = "644" },
]
