name: Release

on:
  push:
    tags:
    - '*'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  fedora:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        fedora: ["39", "40"]
    container:
      image: fedora:${{matrix.fedora}}
    steps:
    - run: cat /etc/fedora-release
    - uses: udoprog/github-release@tag
      id: release
    - uses: actions/checkout@v3
    - uses: udoprog/kick@nightly
    - uses: dtolnay/rust-toolchain@stable
      with:
        targets: wasm32-unknown-unknown
    - uses: Swatinem/rust-cache@v2
    - run: dnf install --assumeyes gcc rpm-build glib2-devel openssl-devel tesseract-devel leptonica-devel clang-devel git
    - uses: udoprog/trunk-action@v1
      with:
        args: build --release crates/web/index.html
    - run: cargo build --release --features gnome,bundle -p jpv
      env:
        JPV_VERSION: ${{steps.release.outputs.tag}}
    - run: kick rpm --version ${{steps.release.outputs.tag}} --append fc${{matrix.fedora}} --output dist
      env:
        RUST_LOG: trace
    - uses: actions/upload-artifact@v3
      with:
        name: dist-fedora-${{matrix.fedora}}
        path: dist

  windows:
    runs-on: windows-latest
    steps:
    - uses: udoprog/github-release@tag
      id: release
    - uses: actions/checkout@v3
    - uses: udoprog/kick@nightly
    - uses: dtolnay/rust-toolchain@stable
      with:
        targets: wasm32-unknown-unknown
    - uses: Swatinem/rust-cache@v2
    - uses: udoprog/trunk-action@v1
      with:
        args: build --release crates/web/index.html
    - run: cargo build --release --features bundle -p jpv
      env:
        JPV_VERSION: ${{steps.release.outputs.tag}}
    - run: kick msi --version ${{steps.release.outputs.tag}} --output dist
    - uses: actions/upload-artifact@v3
      with:
        name: dist-windows
        path: dist

  publish:
    permissions: write-all
    needs: [fedora, windows]
    runs-on: ubuntu-latest
    steps:
    - uses: udoprog/github-release@tag
      id: release
    - uses: actions/checkout@v3
    - uses: actions/download-artifact@v3
      with: {name: dist-fedora-39, path: dist}
    - uses: actions/download-artifact@v3
      with: {name: dist-fedora-40, path: dist}
    - uses: actions/download-artifact@v3
      with: {name: dist-windows, path: dist}
    - uses: udoprog/github-release@v1
      with:
        files: "dist/*"
        name: ${{steps.release.outputs.tag}}
        token: ${{secrets.GITHUB_TOKEN}}
        prerelease: ${{steps.release.outputs.prerelease}}
